name: Jest Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: yarn

      - name: Run the tests
        run: yarn test
